sudo: required
services:
  - docker

before_install:
  - docker build -t andylyell/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andylyell/react-test npm test -- --coverage

after_success:
  - docker build -t andylyell/multi-client ./client
  - docker build -t andylyell/multi-nginx ./nginx
  - docker build -t andylyell/multi-server ./server
  - docker build -t andylyell/multi-worker ./worker
  #Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and push to docker hub
  - docker push andylyell/multi-client 
  - docker push andylyell/multi-nginx
  - docker push andylyell/multi-server
  - docker push andylyell/multi-worker
